var textoEng = '{"Eng":[' +
'{"Tit":"Assembly supervisor support", "image":"img/COMBI_Line.jpeg", "Texto": "Support to the COMBI Line -can and bottle filling- assembly process in the CCC Brewery Plant. This was one of the most challenging jobs that I have had, the team grew to more than 80 people and each detail implied a lot of money, work and responsability.", "url": "http://indismont.com/"},'+
'{"Tit":"Junior Developer - Testing", "image":"", "Texto":"Test and quality assurance for software development. At that time the company was developing a tool for a public department of the country, the goal was make a web app for making simple the access to the information of the public investment in the regions. Then the company started to explore some Big Data tools for identify what people say about that public office over social media", "url": "http://www.iscloudcorporation.com/"},'+
'{"Tit":"Junior Developer - Internship", "image":"img/UFRGS.jpg", "Texto":"Web application development for monitoring medication intake. This project was asked for the Pharmacy Faculty to the research group TEIAS: UFRGS (Universidade Federal do Rio Grande do Sul - BR) Research Center linked to the research lines: Special Education and Inclusive Processes. This experience fostered my programming skills and allow me to approach other process of the research group which called my attention, especially the SCALA one, a web app for storytelling to autistic children.", "url": "https://www.ufrgs.br/teias/"},{"Tit":"Citizen Lab: Collective Intelligence for Democracy", "image":"img/medialabPrado.jpg","Texto":"Medialab Prado is a interdisciplinary public space promoted by the town hall of Madrid. I was part of one of their citizen labs to support de prototyping for better participation in democratic environments. The event got together more than 50 people from around the world, during a hackaton for developing and testing ideas around the use of tecnhology on these kind of topics", "url":"https://www.medialab-prado.es/en/programs/collective-intelligence-democracy", "otros":"-----ACADEMIC EVENTS-----"},{"Tit":"Poster participation: SolBio", "image":"img/solBio.png", "Texto":" IV Argentinian Conference on Computational Biology and Bioinformatics & IV Conference of the Iberoamerican Society for Bioinformatics (SolBio)", "url": "recursos/poster_4CAB.pdf"}],'+
'"Edu":[{"Tit":"Internship Botanical Garden - National University of Colombia San Andrés Island", "image": "img/providencia.JPG", "Texto": "As part of my internship I did practical workshops related with renewable energies and I accompanied an interactive exposition that was design and deployed by the museum of science and game -MCJ-, for the San Andrés island headquarter of the University.", "urlT": "Cien años de soledad, fuente de enseñanza científica en San Andrés", "url":"https://agenciadenoticias.unal.edu.co/detalle/article/cien-anos-de-soledad-fuente-de-ensenanza-cientifica-en-san-andres.html","video":"https://www.youtube.com/embed/BXHllKw-ZaU"}],'+
'"Arts":[{"Tit": "La Visita - Dir. Jose Luis Mondragón", "image":"img/Teatro_LaVisita2.jpg", "Texto": "The Visit is a collective creation based on the master´s thesis of the group´s director, who studied for a master´s degree in Peacebuilding within the framework of the signing of the Peace Agreement with one of the oldest guerrillas on the continent. The play tells the story of a family with many secrets associated with the war and the absence of the father. The creation process led all the members of the group to review their family history and analyze how the internal armed conflict had affected it. The play bets on an intimate theater shared in a home atmosphere"},'+
'{"Tit":"Trabajos de amor perdido - Dir. Hugo Marín", "image":"img/teatro_tDAp.jpeg", "Texto":"A Shakespeare script adapted to the contemporary world using clown language. The play premiered at the La Maldita Vanidad theater in Bogotá"},'+
'{"Tit": "El Siguiente - Dir. Mauricio Córdoba", "image":"img/teatro_ElSiguiente2.jpg", "Texto": "Written by a local screenwriter, the play critiques the Colombian health system. The staging fused the plastic arts, music and acting and the montage was developed by the experimental theater group of the National University of Colombia.", "otros":"img/teatro_clown.gif"}],'+
'"ArtsEduc":['+
'{"Tit": "Párele Bolas - Podcast", "image":"img/pareleBolas.png", "Texto":"A diverse group of people come together to question the existing media and decide to invent an easy-to-listen podcast to discuss politics and current issues","url": "https://www.facebook.com/P%C3%A1rele-bolas-a-108479690497065", "urlT":"FB page","video": "https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/714195421"}],'+
'"EngEducArts":['+
'{"Tit":"Development Creative Engineer! (2019-now)", "image":"img/tecnokids1.png", "Texto":"In charge of promote and teaching programming and basic electronics through workshops for children, young students and teachers as part of Tecnokids program sponsored by the IOM (UN Migration program). In this process I have supported and developed many projects using technology for solving problems identified by the communities itself along the country.", "urlT":"Tecnokids - Creatura Estudio","url": "https://creaturaestudio.com/portfolio_page/tecnokids/", "video": "https://www.youtube.com/embed/GYCcr5e5MpQ"},'+
'{"Tit":"Community artist", "image":"img/EA_1.jpg", "Texto":"In charge of developing artistic experiences oriented to the early childhood (0-5 years), through artistic interventions to different spaces like kindergartens and parks. I chose to try technology as an artistic tool and with my coworker design an installation called -Conexión Selva- using The Makey Makey and a self developed Mobile App. Through this experience kids activate an animal sound when touch me and only with this stimulus they felt encouraged to embody those animals.", "urlT":"Nests Program: Arts in early childhood","url": "https://nidos.gov.co"}'+
']}';

//"https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/714195421
