var textoEng = '{"Eng":[' +
'{"Tit":"Assembly supervisor support", "image":"img/COMBI_Line.jpeg", "Texto": "Support to the COMBI Line -can and bottle filling- assembly process in the CCC Brewery Plant. This was one of the most challenging jobs that I have had, the team grew to more than 80 people and each detail implied a lot of money, work and responsability.", "url": "http://indismont.com/", "urlT":"Indismont.com"},'+
'{"Tit":"Junior Developer - Testing", "Texto":"Test and quality assurance for software development. At that time the company was developing a tool for a public department of the country, the goal was make a web app for making simple the access to the information of the public investment in the regions. Then the company started to explore some Big Data tools for identify what people say about that public office over social media", "url": "http://www.iscloudcorporation.com/", "urlT":"Iscloudcorporation.com"},'+
'{"Tit":"Junior Developer - Internship", "image":"img/UFRGS.jpg", "Texto":"Web application development for monitoring medication intake. This project was asked for the Pharmacy Faculty to the research group TEIAS: UFRGS (Universidade Federal do Rio Grande do Sul - BR) Research Center linked to the research lines: Special Education and Inclusive Processes. This experience fostered my programming skills and allow me to approach other process of the research group which called my attention, especially the SCALA one, a web app for storytelling to children with autism.", "url": "https://www.ufrgs.br/teias/", "urlT":"ufrgs.br/teias"},'+
'{"Tit":"Citizen Lab: Collective Intelligence for Democracy", "image":"img/medialabPrado.jpg","Texto":"Medialab Prado is a interdisciplinary public space promoted by the town hall of Madrid. I was part of one of their citizen labs to support de prototyping for better participation in democratic environments. The event got together more than 50 people from around the world, during a hackaton for developing and testing ideas around the use of tecnhology on these kind of topics", "url":"https://www.medialab-prado.es/en/programs/collective-intelligence-democracy", "urlT":"Collective Intelligence Medialab", "otros":"-----ACADEMIC EVENTS-----"},'+
'{"Tit":"Poster participation: SolBio", "image":"img/solBio.png", "Texto":" IV Argentinian Conference on Computational Biology and Bioinformatics & IV Conference of the Iberoamerican Society for Bioinformatics (SolBio)", "url": "recursos/poster_4CAB.pdf","urlT":"Check our Poster!"}],'+

'"Edu":[{"Tit":"Internship Botanical Garden - National University of Colombia San Andrés Island", "image": "img/providencia.JPG", "Texto": "As part of my internship I did practical workshops related with renewable energies and I accompanied an interactive exposition that was design and deployed by the museum of science and game -MCJ- about One Hundred Years of Solitude, book of the colombian nobel prize in literature Gabriel Garcia Márquez, in the San Andrés island headquarter of the University.", "urlT": "Cien años de soledad, fuente de enseñanza científica en San Andrés", "url":"https://agenciadenoticias.unal.edu.co/detalle/article/cien-anos-de-soledad-fuente-de-ensenanza-cientifica-en-san-andres.html","video":"https://www.youtube.com/embed/BXHllKw-ZaU"}],'+
'"Arts":[{"Tit": "SURcando el tiempo - Dir. Colectivo Nina Sonqo", "image":"img/Teatro_Surcando.jpg", "Texto": "This is a play that delves into the relationship between humans and their natural environment, exploring the normalized behaviors of contemporary society and challenging the hegemonic concept of development. Two researchers from the year 3050 have brought some objects from the ancient planet Earth and share them with the audience, speculating on their use and revealing some of their alarming discoveries about humanity in the 21st century. The script was created by the group as part of a granted given by the Culture secretariat of Nariño State"},'+
'{"Tit": "La Visita - Dir. Jose Luis Mondragón", "image":"img/Teatro_LaVisita2.jpg", "Texto": "The Visit is a collective creation based on the master´s thesis of the group´s director, who studied for a master´s degree in Peacebuilding within the framework of the signing of the Peace Agreement with one of the oldest guerrillas on the continent. The play tells the story of a family with many secrets associated with the war and the absence of the father. The creation process led all the members of the group to review their family history and analyze how the internal armed conflict had affected it. The play bets on an intimate theater shared in a home atmosphere"},'+
'{"Tit":"Trabajos de amor perdido - Dir. Hugo Marín", "image":"img/teatro_tDAp.jpeg", "Texto":"A Shakespeare script adapted to the contemporary world using clown language. The play premiered at the La Maldita Vanidad theater in Bogotá"},'+
'{"Tit": "El Siguiente - Dir. Mauricio Córdoba", "image":"img/teatro_ElSiguiente2.jpg", "Texto": "Written by a local screenwriter, the play critiques the Colombian health system. The staging fused the plastic arts, music and acting and the montage was developed by the experimental theater group of the National University of Colombia."}],'+

'"ArtsEduc":['+
'{"Tit": "Sound Exploration Workshop", "image":"img/Carchi_UPEC.JPEG", "Texto":"At the State Polytechnic University of Carchi (UPEC - Ecuador), we conducted a workshop on theatrical improvisation tools. It was my opportunity to share some experiences related to sound exploration as a resource for scenic creation. UPEC follows a STEAM education model, so the training was aimed at students from various disciplines.","video": "https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/playlists/1728934050"},'+
'{"Tit": "Párele Bolas - Podcast", "image":"img/pareleBolas.png", "Texto":"A diverse group of people come together to question the existing media and decide to invent an easy-to-listen podcast to discuss politics and current issues","url": "https://www.facebook.com/P%C3%A1rele-bolas-a-108479690497065", "urlT":"FB page","video": "https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/714195421"}],'+

'"EngEduc":['+
'{"Tit": "Digital Public Innovation Booster", "image":"img/LogoCIPD.PNG", "Texto":"The Center for Digital Public Innovation – MINTIC (Ministry of Information and Communication Technologies) works for promoting digital public innovation and emerging technologies, focusing primarily on Artificial Intelligence and Blockchain. The objective is to encourage public bodies governed by the National Digital Government policy to adopt these approaches and incorporate user-centered agile methodologies for solving public challenges in Colombia","url": "https://gobiernodigital.mintic.gov.co/portal/Iniciativas/Centro-de-Innovacion-Publica-Digital/", "urlT":"CIPD", "video": "https://www.youtube.com/embed/CtWCbVqoYHw?si=-OlcKg833rywZtiG&amp;start=10720"},'+
'{"Tit": "Vive Maker Co - Hackathon", "image":"img/viveMaker2.jpg", "Texto":"Technical support in workshops as part of a project leads by MINTIC (Ministry of technology and communications). The project was developed in five cities with the purpose of promote solving local problems using technology. We used design thinking, programming and electronic tools for developing prototypes. At the end of the event we carry on a hackathon with the teams who presented their functional ideas.","url": "https://www.mintic.gov.co/portal/inicio/Sala-de-Prensa/Noticias/57705:MinTIC-abre-la-convocatoria-viveMaker-co-para-potencializar-las-capacidades-tecnologicas-de-jovenes-en-cinco-departamentos", "urlT":"Official invitation"},'+
'{"Tit":"Workshop Leader", "image": "img/pixieMinds.jpg", "Texto":"I was in charge of planning and developing workshops related with programming, apps and robotics, especially for children and adolescents. We used tools like App Inventor, robot Edison, robot Sphero, Arduino, etc. Being part of this team I had my first Arduino workshop in a public library, this was a great experience because the attendees excitement, we finished the process being part of the mini Maker Faire Bogotá, and because of this I got the Robotic People Award 2016!","urlT": "PixieMinds", "url": "https://www.pixieminds.com.co/"}],'+

'"ArtsEng":['+
'{"Tit": "Totalidad", "Texto":"Totalidad (Wholeness) is an experimental video project that starts as a continuation of an investigation on pre-Columbian geometries, their constructive logics, the aesthetic enjoyment of form or symbol and its relationship with mysticism, as well as the constant use of the golden ratio. John Melo Visual Artist developed the concept and called me for some visual programming, we worked togheter looking for the generation of an experience. The piece was released in 2019 at the FullDome Festival of Bogotá, and later received the video Experimental Fulldome grant at Jena FullDome Festival 2020", "image": "img/totalidad.gif", "urlT":"John Melo´s web site", "url":"https://johnfmeloa.wixsite.com/johnmelo/totalidad"},'+
'{"Tit":"Etheremick y los Electromagnéticos", "Texto":"Based on the results of the “Irrupción theremin” and “Microphony, Hacking and Creation” laboratories (Bogotá Platform, Idartes. 2017 and 2018 respectively) the “Electromagnetic” collective (Bogotá, 2018) formed by Nina Mesías, Andrés Felipe Forero, Paola Pérez and Erick Suescún (Etheremick), artists from different disciplines interested in hearing, recording and controlling objects that produce electromagnetic fields at inaudible frequencies.", "image":"img/Etheremick.png", "urlT": "Collective´s web site", "url":"https://andresffelipel.wixsite.com/electromagneticos", "video":"https://www.youtube.com/embed/aSoCNLVEdMs"},'+
'{"Tit":"Tal Cosa (That thing)", "image":"img/conjuntoCrisalida.jpg", "Texto":"The Cyborg Dream Laboratory (Media Lab Platform) was the meeting point for a group of artists from different disciplines with the curiosity to explore the new languages that allow the synergy between art and technology. As a result, we present the installation Crisálida, a plastic object built with organic matter but intervened with mapping, sensors and programming. The pupa (Crisálida) interacts with its visitors by reflecting and altering its image and generating a simulated dialogue using the RiTa processing library.", "urlT":"Crisalida project", "url": "https://johnfmeloa.wixsite.com/johnmelo/crisalida"}],'+

'"EngEducArts":['+
'{"Tit":"Development Creative Engineer! (2019-2022)", "image":"img/tecnokids1.png", "Texto":"In charge of promote and teaching programming and basic electronics through workshops for children, young students and teachers as part of Tecnokids program sponsored by the IOM (UN Migration program). In this process I have supported and developed many projects using technology for solving problems identified by the communities itself along the country.", "urlT":"Tecnokids - Creatura Estudio","url": "https://creaturaestudio.com/portfolio_page/tecnokids/", "imgVid": "img/tecnokids2.gif", "imgVidURL": "https://www.youtube.com/watch?v=r1hnoNThhfo&list=PLEMpRDRXKcBB3yRLXTcVb_YKEz4gX7mkR&ab_channel=tecnokids.co"},'+
'{"Tit":"Community artist", "image":"img/EA_1.jpg", "Texto":"In charge of developing artistic experiences oriented to the early childhood (0-5 years), through artistic interventions to different spaces like kindergartens and parks. I chose to try technology as an artistic tool and with my coworker design an installation called -Conexión Selva- using The Makey Makey and a self developed Mobile App. Through this experience kids activate an animal sound when touch me and only with this stimulus they felt encouraged to embody those animals.", "urlT":"Nests Program: Arts in early childhood","url": "https://nidos.gov.co"}'+
']}';

//"https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/714195421


