var textoEng = '{"Eng":[' +
'{"Tit":"Assembly supervisor support", "image":"img/COMBI_Line.jpeg", "Texto": "Support to the COMBI Line -can and bottle filling- assembly process in the CCC Brewery Plant. This was one of the most challenging jobs that I have had, the team grew to more than 80 people and each detail implied a lot of money, work and responsability.", "url": "http://indismont.com/"},'+
'{"Tit":"Junior Developer - Testing", "image":"", "Texto":"Test and quality assurance for software development. At that time the company was developing a tool for a public department of the country, the goal was make a web app for making simple the access to the information of the public investment in the regions. Then the company started to explore some Big Data tools for identify what people say about that public office over social media", "url": "http://www.iscloudcorporation.com/"},'+
'{"Tit":"Junior Developer - Internship", "image":"img/UFRGS.jpg", "Texto":"Web application development for monitoring medication intake. This project was asked for the Pharmacy Faculty to the research group TEIAS: UFRGS (Universidade Federal do Rio Grande do Sul - BR) Research Center linked to the research lines: Special Education and Inclusive Processes. This experience fostered my programming skills and allow me to approach other process of the research group which called my attention, especially the SCALA one, a web app for storytelling to autistic children.", "url": "https://www.ufrgs.br/teias/"},{"Tit":"Citizen Lab: Collective Intelligence for Democracy", "image":"img/medialabPrado.jpg","Texto":"Medialab Prado is a interdisciplinary public space promoted by the town hall of Madrid. I was part of one of their citizen labs to support de prototyping for better participation in democratic environments. The event got together more than 50 people from around the world, during a hackaton for developing and testing ideas around the use of tecnhology on these kind of topics", "url":"https://www.medialab-prado.es/en/programs/collective-intelligence-democracy", "otros":"-----ACADEMIC EVENTS-----"},{"Tit":"Poster participation: SolBio", "image":"img/solBio.png", "Texto":" IV Argentinian Conference on Computational Biology and Bioinformatics & IV Conference of the Iberoamerican Society for Bioinformatics (SolBio)", "url": "recursos/poster_4CAB.pdf"}], "Arts":[' +
'{"Tit":"Community artist", "image":"img/COMBI_Line.jpeg", "Texto":"As an engineer", "url": "http://indismont.com/"},'+
'{"Tit":"Assembly supervisor", "image":"img/COMBI_Line.jpeg", "Texto":"Support to the COMBI Line -can and bottle filling- assembly process in the CCC Brewery Plant. This was one of the most challenging jobs that I have had, the team grew to more than 80 people and each detail implied a lot of money, work and responsability.", "url": "http://indismont.com/"},'+
'{"firstName":"Peter", "lastName":"Jones"}]}';


var text = '{ "employees" : [' +
'{ "firstName":"John" , "lastName":"Doe" },' +
'{ "firstName":"Anna" , "lastName":"Smith" },' +
'{ "firstName":"Peter" , "lastName":"Jones" } ]}';
